name = "Alien-FLTK"
badges = ["travis"]
module_maker="ModuleBuildTiny"
license="artistic_2"
requires_external_bin=["sh');\nuse lib 'inc';\nuse MBTFLTK;\n('1", 'sed']

[release]
pause_config = "C:/Strawberry/pause.upload"

[build]
build_class = "inc::MBTFLTK"
