name = "Alien-FLTK"
badges = ["travis", 'metacpan']
module_maker="ModuleBuildTiny"
license="artistic_2"
authority="cpan:SANKO"
requires_external_bin=["sh');\nuse lib 'inc';\nuse MBTFLTK;\n('1"]

[release]
hook=[
    'tidyall -a'
]